FROM hypriot/rpi-python:latest

RUN apt-get update
RUN apt-get install -y transmission-daemon
RUN service transmission-daemon stop

EXPOSE 9091 9091
EXPOSE 8080 8080

VOLUME /etc/transmission-daemon

COPY xbmc-upd.sh /root/xbmc-upd.sh 
COPY settings.json /root/settings.json

CMD transmission-daemon --foreground --config-dir /root 1>/dev/null 2>/dev/null
