
RUN apt-get update 
RUN apt-get install -y curl && apt-get remove -y python-pip && apt-get clean

RUN curl https://bootstrap.pypa.io/get-pip.py | python
RUN pip install -U pip

COPY flexget/requirements.txt /root/requirements.txt
RUN pip install -r /root/requirements.txt --ignore-installed

VOLUME /root/Storage

COPY make_folders.sh /root/make_folders.sh
COPY flexget/config.yml_template /root/config.yml_template
COPY flexget/install.sh /root/install.sh

CMD /root/install.sh
