
RUN apt-get update 
RUN apt-get install -y curl && apt-get remove -y python-pip && apt-get clean

RUN curl https://bootstrap.pypa.io/get-pip.py | python
RUN pip install -U pip

COPY flexget/requirements.txt /root/requirements.txt
RUN pip install -r /root/requirements.txt --ignore-installed

VOLUME /root/Storage

COPY make_folders.sh flexget/config.yml_template flexget/flexget.sh /root/

CMD /root/install.sh
